services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: param_service
    # No necesitas exponer 5432 al host para que la API lo use.
    # Si quieres usar pgAdmin desde tu host: ports: ["5433:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d param_service"]
      interval: 2s
      timeout: 3s
      retries: 20

  api:
    build: .
    environment:
      APP_ENV: development
      FLASK_DEBUG: "1"
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/param_service
    depends_on:
      db:
        condition: service_healthy
    ports: ["8000:8000"]
    restart: unless-stopped
